BUILD.mdに修正
FascodeNet/alterlinux pull request #177
Opened 2020-08-18 13:45 UTC by YYTU-Aqua

日本語オプションを-g jaに修正しました
必要なパッケージにcmakeとninjaを追加しました

2020-08-18 23:47 UTC, Hayao0819 requested changes

2020-08-18 23:47 UTC, Hayao0819 commented on docs/jp/BUILD.md
> +日本語にする | -g ja
最新の`build.sh`では`-g`が`-l`に変更されています。

2020-08-19 07:47 UTC, YYTU-Aqua commented on docs/jp/BUILD.md
> +日本語にする | -g ja
修正しました
ありがとうございます

2020-08-19 07:48 UTC, Hayao0819 approved these changes

2020-08-19 07:49 UTC, merged